name: prime-cache-9e62e67

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: prime-cache-9e62e67
        uses: actions/checkout@v4

      - name: prime-cache-9e62e67
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: prime-cache-9e62e67
        id: cache-npm-deps 
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-9e62e67

      - name: prime-cache-9e62e67 # <-- This is the display name shown in the UI
        id: prime-cache-9e62e67   # <-- This is the ID used to reference the step
        run: echo "Cache hit was: ${{ steps.cache-npm-deps.outputs.cache-hit }}"

      - name: prime-cache-9e62e67
        # We still refer to the cache step by its ID
        if: steps.cache-npm-deps.outputs.cache-hit != 'true'
        run: npm install

      - name: prime-cache-9e62e67
        run: echo "Running build command..."
